import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import variantsRouter from "./variants";
import ordersRouter from "./orders";
import heldOrdersRouter from "./held-orders";
import quotationsRouter from "./quotations";
import dashboardRouter from "./dashboard";
import customersRouter from "./customers";
import reportsRouter from "./reports";
import tablesRouter from "./tables";
import kitchenRouter from "./kitchen";
import staffRouter from "./staff";
import staffSessionsRouter from "./staff-sessions";
import purchasesRouter from "./purchases";
import purchaseBillsRouter from "./purchase-bills";
import purchaseOrdersRouter from "./purchase-orders";
import cashRouter from "./cash";
import emailRouter from "./email";
import settingsRouter from "./settings";
import saasAuthRouter from "./saas-auth";
import plansRouter from "./plans";
import billingRouter from "./billing";
import superadminRouter from "./superadmin";
import rolesRouter from "./roles";
import locationsRouter from "./locations";
import accountingRouter from "./accounting";
import publicMenuRouter from "./public-menu";
import arRouter from "./ar";
import ingredientsRouter from "./ingredients";
import recipesRouter from "./recipes";
import productionRouter from "./production";
import resellerRouter from "./reseller";
import superadminEmailRouter from "./superadmin-email";
import storeRouter from "./store";
import hardwareRouter from "./hardware";
import vendorsRouter from "./vendors";
import apRouter from "./ap";
import adminUsersRouter from "./admin-users";
import emailTemplatesRouter from "./email-templates";
import auditRouter from "./audit";
import topupRouter from "./topup";
import superadminMarketingRouter from "./superadmin-marketing";
import marketingUnsubscribeRouter from "./marketing-unsubscribe";
import scaleRouter from "./scale";
import businessProfileRouter from "./business-profile";
import productPricingRouter from "./product-pricing";
import productUnitsRouter from "./product-units";
import paymentMethodsRouter from "./payment-methods";
import compositeProductsRouter from "./composite-products";
import techniciansRouter from "./technicians";
import priceManagerRouter from "./price-manager";
import promotionsRouter from "./promotions";
import productBatchesRouter from "./product-batches";
import supplierReturnsRouter from "./supplier-returns";
import overrideCardsRouter from "./override-cards";
import giftVouchersRouter from "./gift-vouchers";
import shopifyRouter from "./shopify";
import superadminAnalyticsRouter from "./superadmin-analytics";
import supportTicketsRouter from "./support-tickets";
import layawaysRouter from "./layaways";
import workOrdersRouter from "./work-orders";
import packagesRouter from "./packages";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(variantsRouter);
router.use(ordersRouter);
router.use(heldOrdersRouter);
router.use(quotationsRouter);
router.use(layawaysRouter);
router.use(workOrdersRouter);
router.use(packagesRouter);
router.use(giftVouchersRouter);
router.use(dashboardRouter);
router.use(customersRouter);
router.use(reportsRouter);
router.use(tablesRouter);
router.use(kitchenRouter);
router.use(staffRouter);
router.use(staffSessionsRouter);
router.use(purchasesRouter);
router.use(purchaseBillsRouter);
router.use(purchaseOrdersRouter);
router.use(cashRouter);
router.use(emailRouter);
router.use(settingsRouter);
router.use(saasAuthRouter);
router.use(plansRouter);
router.use(billingRouter);
router.use(superadminRouter);
router.use(superadminAnalyticsRouter);
router.use(rolesRouter);
router.use(locationsRouter);
router.use(accountingRouter);
router.use(publicMenuRouter);
router.use(arRouter);
router.use(ingredientsRouter);
router.use(recipesRouter);
router.use(productionRouter);
router.use(resellerRouter);
router.use(superadminEmailRouter);
router.use(storeRouter);
router.use(hardwareRouter);
router.use(vendorsRouter);
router.use(apRouter);
router.use(adminUsersRouter);
router.use("/email-templates", emailTemplatesRouter);
router.use(auditRouter);
router.use(topupRouter);
router.use(superadminMarketingRouter);
router.use(marketingUnsubscribeRouter);
router.use(scaleRouter);
router.use(businessProfileRouter);
router.use(productPricingRouter);
router.use(productUnitsRouter);
router.use(paymentMethodsRouter);
router.use(compositeProductsRouter);
router.use(techniciansRouter);
router.use(priceManagerRouter);
router.use(promotionsRouter);
router.use(productBatchesRouter);
router.use(supplierReturnsRouter);
router.use(overrideCardsRouter);
router.use(shopifyRouter);
router.use(supportTicketsRouter);

export default router;
