import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import variantsRouter from "./variants";
import ordersRouter from "./orders";
import heldOrdersRouter from "./held-orders";
import dashboardRouter from "./dashboard";
import customersRouter from "./customers";
import reportsRouter from "./reports";
import tablesRouter from "./tables";
import kitchenRouter from "./kitchen";
import staffRouter from "./staff";
import purchasesRouter from "./purchases";
import purchaseBillsRouter from "./purchase-bills";
import cashRouter from "./cash";
import emailRouter from "./email";
import settingsRouter from "./settings";
import saasAuthRouter from "./saas-auth";
import plansRouter from "./plans";
import billingRouter from "./billing";
import superadminRouter from "./superadmin";
import rolesRouter from "./roles";
import locationsRouter from "./locations";
import accountingRouter from "./accounting";
import publicMenuRouter from "./public-menu";
import arRouter from "./ar";
import ingredientsRouter from "./ingredients";
import recipesRouter from "./recipes";
import productionRouter from "./production";
import resellerRouter from "./reseller";
import superadminEmailRouter from "./superadmin-email";
import storeRouter from "./store";
import hardwareRouter from "./hardware";
import vendorsRouter from "./vendors";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(variantsRouter);
router.use(ordersRouter);
router.use(heldOrdersRouter);
router.use(dashboardRouter);
router.use(customersRouter);
router.use(reportsRouter);
router.use(tablesRouter);
router.use(kitchenRouter);
router.use(staffRouter);
router.use(purchasesRouter);
router.use(purchaseBillsRouter);
router.use(cashRouter);
router.use(emailRouter);
router.use(settingsRouter);
router.use(saasAuthRouter);
router.use(plansRouter);
router.use(billingRouter);
router.use(superadminRouter);
router.use(rolesRouter);
router.use(locationsRouter);
router.use(accountingRouter);
router.use(publicMenuRouter);
router.use(arRouter);
router.use(ingredientsRouter);
router.use(recipesRouter);
router.use(productionRouter);
router.use(resellerRouter);
router.use(superadminEmailRouter);
router.use(storeRouter);
router.use(hardwareRouter);
router.use(vendorsRouter);

export default router;
